version: '3'
services:
  pg:
    container_name: postgres_container
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=study-habr
    ports:
      - '5432:5432'
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - pg
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pgadmin:
